/**
 * @fileoverview Policy Generator
 *
 * 可視化データ（検出結果、イベントログ）からセキュリティポリシーを自動提案する。
 * - AI利用ポリシー
 * - データ保護ポリシー
 * - 拡張機能ポリシー
 */

import type { ExtendedProvider } from "./provider-classifier.js";

// ============================================================================
// Types
// ============================================================================

/**
 * ポリシールール
 */
export interface PolicyRule {
  id: string;
  name: string;
  description: string;
  category: PolicyCategory;
  severity: "critical" | "high" | "medium" | "low";
  action: AIPolicyAction;
  condition: PolicyCondition;
  enabled: boolean;
  autoGenerated: boolean;
  confidence: "high" | "medium" | "low";
  reason: string;
}

/**
 * ポリシーカテゴリ
 */
export type PolicyCategory =
  | "ai_usage" // AI利用制限
  | "data_protection" // データ保護
  | "extension" // 拡張機能制限
  | "domain" // ドメイン制限
  | "authentication"; // 認証関連

/**
 * ポリシーアクション
 */
export type AIPolicyAction = "allow" | "warn";

/**
 * ポリシー条件
 */
export interface PolicyCondition {
  type: ConditionType;
  value: string | string[] | number;
  operator?: "equals" | "contains" | "matches" | "gt" | "lt";
}

export type ConditionType =
  | "ai_provider" // AIプロバイダー
  | "data_classification" // データ分類
  | "extension_id" // 拡張機能ID
  | "domain" // ドメイン
  | "risk_score"; // リスクスコア

/**
 * ポリシー生成用の入力データ
 */
export interface PolicyGenerationInput {
  aiUsage?: AIUsageData[];
  dlpDetections?: DLPDetectionData[];
  extensionRisks?: ExtensionRiskData[];
  domainVisits?: DomainVisitData[];
}

export interface AIUsageData {
  provider: ExtendedProvider;
  domain: string;
  promptCount: number;
  hasSensitiveData: boolean;
  riskLevel: string;
}

export interface DLPDetectionData {
  classification: string;
  detectionCount: number;
  highConfidenceCount: number;
  affectedDomains: string[];
}

export interface ExtensionRiskData {
  extensionId: string;
  extensionName: string;
  riskScore: number;
  riskLevel: string;
  flags: string[];
}

export interface DomainVisitData {
  domain: string;
  visitCount: number;
  hasLogin: boolean;
  isNRD: boolean;
  isTyposquat: boolean;
}

/**
 * ポリシー生成結果
 */
export interface PolicyGenerationResult {
  rules: PolicyRule[];
  summary: {
    totalSuggestions: number;
    byCategoryCount: Record<PolicyCategory, number>;
    byActionCount: Record<AIPolicyAction, number>;
    highPriorityCount: number;
  };
  timestamp: number;
}

// ============================================================================
// Policy Generator
// ============================================================================

/**
 * ポリシー自動生成器を作成
 */
export function createPolicyGenerator() {
  /**
   * データからポリシーを生成
   */
  function generate(input: PolicyGenerationInput): PolicyGenerationResult {
    const rules: PolicyRule[] = [];

    // AI利用ポリシー生成
    if (input.aiUsage) {
      for (const r of generateAIPolicies(input.aiUsage)) rules.push(r);
    }

    // データ保護ポリシー生成
    if (input.dlpDetections) {
      for (const r of generateDLPPolicies(input.dlpDetections)) rules.push(r);
    }

    // 拡張機能ポリシー生成
    if (input.extensionRisks) {
      for (const r of generateExtensionPolicies(input.extensionRisks)) rules.push(r);
    }

    // ドメインポリシー生成
    if (input.domainVisits) {
      for (const r of generateDomainPolicies(input.domainVisits)) rules.push(r);
    }

    // サマリー作成
    const summary = createSummary(rules);

    return {
      rules,
      summary,
      timestamp: Date.now(),
    };
  }

  return { generate };
}

// ============================================================================
// Policy Generators
// ============================================================================

/**
 * AI利用ポリシーを生成
 */
function generateAIPolicies(usageData: AIUsageData[]): PolicyRule[] {
  const rules: PolicyRule[] = [];

  // Shadow AIプロバイダーの検出
  const unknownProviders = usageData.filter(
    (u) => u.provider === "unknown" || !isApprovedProvider(u.provider)
  );

  if (unknownProviders.length > 0) {
    const domains = [...new Set(unknownProviders.map((u) => u.domain))];
    rules.push({
      id: "ai-unknown-provider",
      name: "未承認AIサービスの利用制限",
      description: `未承認のAIサービスへのアクセスが${unknownProviders.length}件検出されました`,
      category: "ai_usage",
      severity: "high",
      action: "warn",
      condition: {
        type: "ai_provider",
        value: ["unknown"],
        operator: "equals",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: `検出ドメイン: ${domains.slice(0, 3).join(", ")}${domains.length > 3 ? "..." : ""}`,
    });
  }

  // 機密データを含むAI利用
  const sensitiveUsage = usageData.filter((u) => u.hasSensitiveData);
  if (sensitiveUsage.length > 0) {
    rules.push({
      id: "ai-sensitive-data",
      name: "機密データのAI送信制限",
      description: "機密情報を含むプロンプトのAI送信を警告",
      category: "ai_usage",
      severity: "critical",
      action: "warn",
      condition: {
        type: "data_classification",
        value: ["credentials", "pii", "financial"],
        operator: "contains",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: `${sensitiveUsage.length}件の機密データ送信を検出`,
    });
  }

  // 地域特化型プロバイダー
  const regionalProviders = usageData.filter((u) =>
    isRegionalProvider(u.provider)
  );
  if (regionalProviders.length > 0) {
    rules.push({
      id: "ai-regional-provider",
      name: "地域特化型AIサービスの監視",
      description: "海外地域のAIサービス利用を監視",
      category: "ai_usage",
      severity: "medium",
      action: "allow",
      condition: {
        type: "ai_provider",
        value: ["deepseek", "moonshot", "zhipu", "baidu", "alibaba"],
        operator: "contains",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "medium",
      reason: "データ所在地に関するコンプライアンス確認推奨",
    });
  }

  return rules;
}

/**
 * データ保護ポリシーを生成
 */
function generateDLPPolicies(detections: DLPDetectionData[]): PolicyRule[] {
  const rules: PolicyRule[] = [];

  // 資格情報の検出
  const credentialDetections = detections.filter(
    (d) => d.classification === "credentials"
  );
  if (credentialDetections.length > 0) {
    const totalDetections = credentialDetections.reduce(
      (sum, d) => sum + d.detectionCount,
      0
    );
    rules.push({
      id: "dlp-credentials",
      name: "資格情報漏洩防止",
      description: "APIキー、パスワード等の外部送信をブロック",
      category: "data_protection",
      severity: "critical",
      action: "warn",
      condition: {
        type: "data_classification",
        value: "credentials",
        operator: "equals",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: `${totalDetections}件の資格情報パターンを検出`,
    });
  }

  // 金融情報の検出
  const financialDetections = detections.filter(
    (d) => d.classification === "financial"
  );
  if (financialDetections.length > 0) {
    rules.push({
      id: "dlp-financial",
      name: "金融情報保護",
      description: "クレジットカード番号、口座情報の送信を警告",
      category: "data_protection",
      severity: "high",
      action: "warn",
      condition: {
        type: "data_classification",
        value: "financial",
        operator: "equals",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: "金融情報の外部送信リスクを軽減",
    });
  }

  // 個人情報の検出
  const piiDetections = detections.filter((d) => d.classification === "pii");
  if (piiDetections.length > 0) {
    const affectedDomains = [
      ...new Set(piiDetections.flatMap((d) => d.affectedDomains)),
    ];
    rules.push({
      id: "dlp-pii",
      name: "個人情報保護",
      description: "メールアドレス、電話番号等のPII送信を監視",
      category: "data_protection",
      severity: "medium",
      action: "warn",
      condition: {
        type: "data_classification",
        value: "pii",
        operator: "equals",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "medium",
      reason: `${affectedDomains.length}ドメインでPII送信を検出`,
    });
  }

  return rules;
}

/**
 * 拡張機能ポリシーを生成
 */
function generateExtensionPolicies(risks: ExtensionRiskData[]): PolicyRule[] {
  const rules: PolicyRule[] = [];

  // 高リスク拡張機能
  const highRiskExtensions = risks.filter(
    (r) => r.riskLevel === "critical" || r.riskLevel === "high"
  );
  if (highRiskExtensions.length > 0) {
    for (const ext of highRiskExtensions.slice(0, 3)) {
      rules.push({
        id: `ext-${ext.extensionId}`,
        name: `危険な拡張機能: ${ext.extensionName}`,
        description: ext.flags.slice(0, 2).join(", ") || "高リスク検出",
        category: "extension",
        severity: ext.riskLevel === "critical" ? "critical" : "high",
        action: "warn",
        condition: {
          type: "extension_id",
          value: ext.extensionId,
          operator: "equals",
        },
        enabled: true,
        autoGenerated: true,
        confidence: "high",
        reason: `リスクスコア: ${ext.riskScore}`,
      });
    }
  }

  return rules;
}

/**
 * ドメインポリシーを生成
 */
function generateDomainPolicies(visits: DomainVisitData[]): PolicyRule[] {
  const rules: PolicyRule[] = [];

  // NRD（新規登録ドメイン）でのログイン
  const nrdWithLogin = visits.filter((v) => v.isNRD && v.hasLogin);
  if (nrdWithLogin.length > 0) {
    rules.push({
      id: "domain-nrd-login",
      name: "新規ドメインでのログイン警告",
      description: "最近登録されたドメインでの認証を警告",
      category: "domain",
      severity: "high",
      action: "warn",
      condition: {
        type: "domain",
        value: nrdWithLogin.map((v) => v.domain),
        operator: "contains",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: `${nrdWithLogin.length}件のNRDでログインを検出`,
    });
  }

  // タイポスクワッティング
  const typosquatDomains = visits.filter((v) => v.isTyposquat);
  if (typosquatDomains.length > 0) {
    rules.push({
      id: "domain-typosquat",
      name: "タイポスクワッティング警告",
      description: "偽装ドメインへのアクセスをブロック",
      category: "domain",
      severity: "critical",
      action: "warn",
      condition: {
        type: "domain",
        value: typosquatDomains.map((v) => v.domain),
        operator: "contains",
      },
      enabled: true,
      autoGenerated: true,
      confidence: "high",
      reason: `${typosquatDomains.length}件のタイポスクワッティング検出`,
    });
  }

  return rules;
}

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * 承認済みプロバイダーか
 */
function isApprovedProvider(provider: ExtendedProvider): boolean {
  const approved: ExtendedProvider[] = [
    "openai",
    "anthropic",
    "google",
    "azure",
  ];
  return approved.includes(provider);
}

/**
 * 地域特化型プロバイダーか
 */
function isRegionalProvider(provider: ExtendedProvider): boolean {
  const regional: ExtendedProvider[] = [
    "deepseek",
    "moonshot",
    "zhipu",
    "baidu",
    "alibaba",
  ];
  return regional.includes(provider);
}

/**
 * サマリーを作成
 */
function createSummary(
  rules: PolicyRule[]
): PolicyGenerationResult["summary"] {
  const byCategoryCount: Record<PolicyCategory, number> = {
    ai_usage: 0,
    data_protection: 0,
    extension: 0,
    domain: 0,
    authentication: 0,
  };

  const byActionCount: Record<AIPolicyAction, number> = {
    allow: 0,
    warn: 0,
  };

  let highPriorityCount = 0;

  for (const rule of rules) {
    byCategoryCount[rule.category]++;
    byActionCount[rule.action]++;
    if (rule.severity === "critical" || rule.severity === "high") {
      highPriorityCount++;
    }
  }

  return {
    totalSuggestions: rules.length,
    byCategoryCount,
    byActionCount,
    highPriorityCount,
  };
}

export type PolicyGenerator = ReturnType<typeof createPolicyGenerator>;
